### ISSUE TITLE
linalg error for certain sequences

### ISSUE THREAD

**Issue by lschaerfen** [ViennaRNA/drtransformer#2]
Hi,

I'm getting the error below after a while when I use DrTransformer with certain sequences. I provided one of the sequences that causes this error below. Other sequences make it through without errors. Any chance this could be fixed / any idea what the issue is? Here is the command I'm running. Thank you!

`cat input.fasta | DrTransformer --name test --outdir output --t-ext 0.04 --t-end 3600 --temp 30.0 --stdout OFF`

```
AUGGCUAUUGAUGCUCAAAAGCUUGUGGUGGUCAUCGUGAUCGUGGUCGUGCCUUUGCUCUUCAAGUUCAUUAUCGGACCGAAGACCAAGCCUGUGCUGGAUCCCAAAAGGAAUGACUUCCAAUCAUUUCCGCUGGUUGAAAAAACCAUCUUAACGCAUAAUACUUCGAUGUACAAGUUCGGGCUACCUCAUGCUGACGACGUACUCGGUUUACCAAUUGGUCAGCAUAUCGUAAUUAAGGCCAAUAUCAAUGGUAAGGAUAUUACCAGAUCGUAUACGCCCACAUCGUUGGAUGGAGAUACAAAGGGAAACUUUGAAUUACUAGUGAAGUCUUACCCCACAGGUAACGUUUCUAAGAUGAUUGGAGAGUUGAAGAUAGGUGACUCGAUCCAGAUCAAGGGCCCUCGUGGGAACUAUCAUUAUGAGAGAAACUGCCGUUCCCAUCUAGGGAUGAUUGCUGGUGGUACUGGUAUUGCGCCCAUGUAUCAGAUCAUGAAAGCUAUUGCCAUGGACCCUCACGACACUACCAAGGUCUCUCUAGUCUUUGGGAACGUCCAUGAGGAGGAUAUUCUGUUGAAGAAGGAACUGGAAGCGUUGGUGGCCAUGAAGCCUUCCCAAUUUAAGAUAGUUUACUACUUAGACUCUCCUGACCGUGAAGACUGGACUGGUGGUGUAGGAUACAUUACCAAGGAUGUCAUCAAGGAACACUUGCCCGCUGCUACAAUGGACAACGUUCAAAUUUUGAUCUGUGGUCCUCCAGCCAUGGUUGCCUCAGUUAGAAGAAGUACCGUGGACUUGGGGUUCAGACGUUCCAAACCGCUUUCCAAGAUGGAAGACCAGGUGUUUGUGUUUUAA
```

```
Traceback (most recent call last):
  File ".../conda_envs/standard_38/lib/python3.8/site-packages/drtransformer/linalg.py",
 line 185, in mx_simulate
    raise MxLinalgError(f"CL * CR != I")
drtransformer.linalg.MxLinalgError: CL * CR != I

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../conda_envs/standard_38/bin/DrTransformer", line 8, in <module>
    sys.exit(main())
  File ".../conda_envs/standard_38/lib/python3.8/site-packages/drtransformer/drtransform
er.py", line 480, in main
    for (t, pt) in TL.simulate(snodes, p0, times, force=[t1]):
  File ".../conda_envs/standard_38/lib/python3.8/site-packages/drtransformer/landscape.p
y", line 390, in simulate
    for t, pt in mx_simulate(R, p0, times, force = force, atol = atol, rtol = rtol):
  File ".../conda_envs/standard_38/lib/python3.8/site-packages/drtransformer/linalg.py",
 line 210, in mx_simulate
    raise MxLinalgError(f'Unstable simulation at time {t=}: {sum(pt)=}')
drtransformer.linalg.MxLinalgError: Unstable simulation at time t=0.004: sum(pt)=nan
```

**Comment by bad-ants-fleet** [comment]
Hi Leo,

Unfortunately I don't think I can fix this issue directly, as the solvers have limitations. At some point the landscape is simply to large and some transition rates become extremely small. 

You can reduce the number of simulated structures using the --o-prune parameter, which discards a specified fraction of the ensemble after each simulation. Try --o-prune 0.1 and see if it runs through, but there is still no guarantee. (That's also the parameter we used for the paper with long sequences, but they were still shorter than your 856 nt sequence.) 

The option --profile gives you a summary on how many local minima (lmins) and transitions (moves) are simulated at each nucleotide. I haven't run your example, but I'm expecting this numbers become quite large before the simulations break. 

cat input.fasta | DrTransformer --name test --outdir output --t-ext 0.04 --t-end 3600 --temp 30.0 --o-prune 0.1 --logfile --profile > output/test.prof
